[project]
name = "lzy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.11.4",
    "pydantic-ai>=0.1.11",
    "setuptools>=80.4.0",
]
